// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logisticRWMHcond
Rcpp::List logisticRWMHcond(int N, int nbAdaptMarche, arma::vec y, arma::mat X, arma::vec maxBinom, std::vector<double> curr, std::vector<double> SigMarch, std::vector<std::vector<double>> prior, const int warmup, const double invTemp);
RcppExport SEXP _BayesMixtReg_logisticRWMHcond(SEXP NSEXP, SEXP nbAdaptMarcheSEXP, SEXP ySEXP, SEXP XSEXP, SEXP maxBinomSEXP, SEXP currSEXP, SEXP SigMarchSEXP, SEXP priorSEXP, SEXP warmupSEXP, SEXP invTempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nbAdaptMarche(nbAdaptMarcheSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type maxBinom(maxBinomSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type curr(currSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type SigMarch(SigMarchSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< const double >::type invTemp(invTempSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticRWMHcond(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp));
    return rcpp_result_gen;
END_RCPP
}
// logisticRWMHjoint
Rcpp::List logisticRWMHjoint(int N, int nbAdaptMarche, arma::vec y, arma::mat X, arma::vec maxBinom, arma::vec curr, arma::mat SigMarch, std::vector<arma::vec> prior, const int warmup, const double invTemp);
RcppExport SEXP _BayesMixtReg_logisticRWMHjoint(SEXP NSEXP, SEXP nbAdaptMarcheSEXP, SEXP ySEXP, SEXP XSEXP, SEXP maxBinomSEXP, SEXP currSEXP, SEXP SigMarchSEXP, SEXP priorSEXP, SEXP warmupSEXP, SEXP invTempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type nbAdaptMarche(nbAdaptMarcheSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type maxBinom(maxBinomSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type curr(currSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigMarch(SigMarchSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::vec> >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const int >::type warmup(warmupSEXP);
    Rcpp::traits::input_parameter< const double >::type invTemp(invTempSEXP);
    rcpp_result_gen = Rcpp::wrap(logisticRWMHjoint(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesMixtReg_logisticRWMHcond", (DL_FUNC) &_BayesMixtReg_logisticRWMHcond, 10},
    {"_BayesMixtReg_logisticRWMHjoint", (DL_FUNC) &_BayesMixtReg_logisticRWMHjoint, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesMixtReg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
