# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Logistic binomial regression / conditional inference with RWMH method 
#'
#' @description Performs logistic binomial regression using the RWMH method to infer the coefficients conditionally
#'
#' @param N the number of iterations post-adaptative step
#' @param nbAdaptMarche the number of adaptation steps, one step equals 100 iterations
#' @param y a vector of count values, from 0 to maxBinom[i] for y[i], i in 1...length(y)
#' @param X a matrix of covariates, with dim(X)[1] = length(y)
#' @param maxBinom a vector of maximum trials (in binomial fashion), length(maxBinom) = length(y)
#' @param curr a vector of initialization values corresponding to each of the covariates in the columns of X, ordered in the same way
#' @param SigMarch a covariance matrix for the Gaussian proposal distribution
#' @param prior a list of vectors for the priors' hyperparameters
#' @param warmup the number of iterations reserved to warmup (warmup >= 0 and warmup <= N)
#' @param invTemp a value to temper the likelihood
#' @return a list that includes a matrix of each coefficient posterior sample and the adapted covariance matrix for the Gaussian proposal distribution
.logisticRWMHcond <- function(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup = 0L, invTemp = 1) {
    .Call(`_BayesMixtReg_logisticRWMHcond`, N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp)
}

#' Logistic binomial regression / joint inference with RWMH method 
#'
#' @description This function performs a logistic binomial regression using the RWMH method to jointly infer the coefficients.
#'
#' @param N the number of iterations post-adaptative step
#' @param nbAdaptMarche the number of adaptation steps, one step equals 100 iterations
#' @param y a vector of count values, from 0 to maxBinom[i] for y[i], i in 1...length(y)
#' @param X a matrix of covariates, with dim(X)[1] = length(y)
#' @param maxBinom a vector of maximum trials (in binomial fashion), length(maxBinom) = length(y)
#' @param curr a vector of initialization values corresponding to each of the covariates in the columns of X, ordered in the same way
#' @param SigMarch a covariance matrix for the Gaussian proposal distribution
#' @param prior a list of vectors for the priors' hyperparameters
#' @param warmup the number of iterations reserved to warmup (warmup >= 0 and warmup <= N)
#' @param invTemp a value to temper the likelihood
#' @return a list that includes a matrix of each coefficient posterior sample, the adapted covariance matrix for the Gaussian proposal distribution and some values to compute WAIC
.logisticRWMHjoint <- function(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup = 0L, invTemp = 1) {
    .Call(`_BayesMixtReg_logisticRWMHjoint`, N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp)
}

