# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logisticRWMHcond <- function(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup = 0L, invTemp = 1) {
    .Call(`_BayesMixtReg_logisticRWMHcond`, N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp)
}

logisticRWMHjoint <- function(N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup = 0L, invTemp = 1) {
    .Call(`_BayesMixtReg_logisticRWMHjoint`, N, nbAdaptMarche, y, X, maxBinom, curr, SigMarch, prior, warmup, invTemp)
}

